#background_opacity = 1
import = ["/home/bedgirb/.config/alacritty/colors.toml", "/home/bedgirb/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"

[window]
decorations = "full"
dynamic_title = true
# history = 1000
# multiplie = 3
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 5
y = 5
